eagle

diff --git a/jenkinsfile_2 b/jenkinsfile_2
--- a/jenkinsfile_2
+++ b/jenkinsfile_2
@@ -1,4 +1,3 @@
-// Required imports and dependencies
 @Library('jenkins-sharedlib') _
 import com.cloudbees.jenkins.plugins.awscredentials.*
 import com.cloudbees.plugins.credentials.*
@@ -8,8 +7,9 @@ import jenkins.model.Jenkins
 STATIC_NOTIFICATION_LIST = "ladsdc@ice.dhs.gov"
 VAULT_MANAGED_APP_ROLE = 'managed_vault_approle'
 CB_SECRET_PATH = 'secret/managed/cloudbees/shared'
+CTLR_NAME = 'aws'
 
-// Define the ActiveJenkinsAgent class needed for agent management
+// Active Jenkins Agent Class Definition
 class ActiveJenkinsAgent implements Serializable {
     def script
     String awsInstanceId
@@ -25,7 +25,6 @@ class ActiveJenkinsAgent implements Serializable {
         this.jenkinsName = jenkinsName
         this.ctlrName = ctlrName
         
-        // Parse the AWS launch time
         def launchTime = script.sh(
             returnStdout: true,
             script: "aws ec2 describe-instances --instance-ids ${awsInstanceId} --query 'Reservations[].Instances[].LaunchTime' --output text"
@@ -40,15 +39,11 @@ pipeline {
             label 'sdo-jenkins'
         }
     }
-    
+
     environment {
         CTLR_NAME = 'aws'
         DEBUG = true
-        // AWS and Vault credentials will be needed
-        AWS_CREDENTIALS = credentials('aws-credentials-id')
-        VAULT_CREDENTIALS = credentials('vault-credentials-id')
-        // CloudBees credentials
-        CB_CREDENTIALS = credentials('cloudbees-credentials-id')
+        IS_MAIN = env.BRANCH_NAME == 'main' || env.BRANCH_NAME == 'master'
     }
 
     stages {
@@ -62,80 +57,76 @@ pipeline {
             }
         }
 
-        stage('Remove all but latest 2 Jenkins Agents') {
+        stage('Detach Nodes') {
+            when {
+                expression { IS_MAIN }
+            }
             steps {
                 script {
-                    withCredentials([
-                        [$class: 'AWSCredentialsBinding', 
-                         credentialsId: 'aws-credentials-id',
-                         accessKeyVariable: 'AWS_ACCESS_KEY_ID', 
-                         secretKeyVariable: 'AWS_SECRET_ACCESS_KEY'],
-                        [$class: 'VaultTokenCredentialBinding',
-                         credentialsId: 'vault-credentials-id',
-                         vaultAddr: vaultUrl]
-                    ]) {
-                        withVault(configuration: vaultConfig, vaultSecrets: secrets) {
-                            // Get current node information
-                            def currentNodeName = env.NODE_NAME
-                            def currentNodeId = sh(
-                                returnStdout: true,
-                                script: "aws ec2 describe-instances --filters 'Name=tag:Name,Values=${currentNodeName}' --query 'Reservations[*].Instances[*].[InstanceId]' --output text"
-                            ).trim()
-                            
-                            echo "Current node: ${currentNodeName} (${currentNodeId})"
-                            
-                            // Get list of agents using CloudBees API
-                            def cloudbeesAgentsInfo = cloudBeesUtils.getAgentsList(CTLR_NAME)
-                            def activeAgentsList = []
-                            def currentAgent = null
-                            
-                            // Process each agent
-                            cloudbeesAgentsInfo.each { agentInfo ->
-                                def aws_instanceId = jenkinsAgents.getAwsInstanceId(agentInfo.name)
-                                
-                                if (aws_instanceId) {
-                                    def activeAgent = new ActiveJenkinsAgent(
-                                        this, 
-                                        aws_instanceId, 
-                                        agentInfo.name,
-                                        agentInfo.displayName,
-                                        CTLR_NAME
-                                    )
-                                    if (aws_instanceId.contains(currentNodeId)) {
-                                        currentAgent = activeAgent
-                                    }
-                                    activeAgentsList.add(activeAgent)
-                                }
+                    // Get current node information
+                    def currentNodeName = env.NODE_NAME
+                    def currentNodeId = sh(
+                        returnStdout: true,
+                        script: "aws ec2 describe-instances --filters 'Name=tag:Name,Values=${currentNodeName}' --query 'Reservations[*].Instances[*].[InstanceId]' --output text"
+                    ).trim()
+                    
+                    echo "Current node: ${currentNodeName} (${currentNodeId})"
+                    
+                    // Get agents list from parameter or another job
+                    def agentsToDetach = params.AGENTS_TO_DETACH.split(',')
+                    def currentAgentInfo = null
+                    def newestAgent = null
+                    
+                    CCloudbeeUtils.vaultCredBindingWrapper(CTLR_NAME, { cbId, cbToken ->
+                        // Get newest agent for transfer
+                        def newestAgentResponse = sh(
+                            returnStdout: true,
+                            script: """
+                                curl -s -H '${cbId}:${cbToken}' 'https://cloudbees.ice.dhs.gov/ems/computer/api/json?tree=computer[displayName,description,assignedLabels[name],launchTime]&pretty=0' | \
+                                jq -r '.computer[] | select(.assignedLabels[].name == "sdo-jenkins") | "\(.displayName),\(.description),\(.launchTime)"' | \
+                                sort -t',' -k3 -r | head -n 1
+                            """
+                        ).trim()
+                        
+                        newestAgent = newestAgentResponse.split(',')[0]
+                        
+                        // Process detachment
+                        agentsToDetach.each { agentName ->
+                            if (agentName == currentNodeName) {
+                                currentAgentInfo = agentName
+                                return // skip current agent
                             }
                             
-                            // Sort agents by creation date
-                            activeAgentsList.sort { a, b -> b.awsCreatedOnDate <=> a.awsCreatedOnDate }
+                            // Detach other agents
+                            echo "Detaching agent: ${agentName}"
+                            jenkinsAgents.doDetach(agentName, CTLR_NAME, false)
+                        }
+                        
+                        // Handle current agent last if it's in the list
+                        if (currentAgentInfo) {
+                            echo "Handling current agent detachment..."
                             
-                            // Handle cleanup
-                            if (activeAgentsList.indexOf(currentAgent) < 2) {
-                                echo "Current agent is one of the latest 2, proceeding with normal cleanup"
-                                removeOldAgents(activeAgentsList, 2)
+                            echo "Attempting to transfer job to newest agent: ${newestAgent}"
+                            def success = sh(
+                                script: """
+                                    jenkins-cli -s http://${newestAgent}:8080 build ${env.JOB_NAME} -p TRANSFER_FROM=${currentNodeName} || exit 1
+                                    sleep 30  # Wait for job to start on new agent
+                                    if curl -s http://${newestAgent}:8080/job/${env.JOB_NAME}/lastBuild/api/json | grep '"building":true'; then
+                                        exit 0
+                                    else
+                                        exit 1
+                                    fi
+                                """,
+                                returnStatus: true
+                            ) == 0
+                            
+                            if (success) {
+                                echo "Job successfully transferred, current agent will be detached by new instance"
                             } else {
-                                echo "Current agent is older, initiating special cleanup sequence"
-                                def newestAgent = activeAgentsList[0]
-                                
-                                // Transfer job to newest agent
-                                def success = transferJob(newestAgent.wsName, currentNodeName)
-                                
-                                if (success) {
-                                    echo "Job successfully transferred, cleaning up old agents except current"
-                                    def agentsToKeep = [activeAgentsList[0], activeAgentsList[1], currentAgent]
-                                    activeAgentsList.each { agent ->
-                                        if (!agentsToKeep.contains(agent)) {
-                                            jenkinsAgents.doDetach(agent.jenkinsName, CTLR_NAME, false)
-                                        }
-                                    }
-                                } else {
-                                    error "Failed to transfer job to new agent, aborting cleanup"
-                                }
+                                error "Failed to transfer job to new agent, aborting cleanup"
                             }
                         }
-                    }
+                    })
                 }
             }
         }
@@ -145,34 +136,11 @@ pipeline {
         failure {
             script {
                 emailext(
-                    subject: "Jenkins Agent Cleanup Failed - ${env.JOB_NAME} #${env.BUILD_NUMBER}",
-                    body: "The Jenkins agent cleanup job failed. Please check the logs.",
+                    subject: "Jenkins Agent Detach Failed - ${env.JOB_NAME} #${env.BUILD_NUMBER}",
+                    body: "The Jenkins agent detach job failed. Please check the logs.",
                     to: STATIC_NOTIFICATION_LIST
                 )
             }
         }
-    }
-}
-
-// Helper functions
-def transferJob(newAgentName, currentNodeName) {
-    return sh(
-        script: """
-            jenkins-cli -s http://${newAgentName}:8080 build ${env.JOB_NAME} -p TRANSFER_FROM=${currentNodeName} || exit 1
-            sleep 30  # Wait for job to start on new agent
-            if curl -s http://${newAgentName}:8080/job/${env.JOB_NAME}/lastBuild/api/json | grep '"building":true'; then
-                exit 0
-            else
-                exit 1
-            fi
-        """,
-        returnStatus: true
-    ) == 0
-}
-
-def removeOldAgents(agentsList, keepCount) {
-    def agentsToRemove = agentsList[keepCount..-1]
-    agentsToRemove.each { agent ->
-        jenkinsAgents.doDetach(agent.jenkinsName, CTLR_NAME, false)
     }
 }
